/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rjjohnson
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromButtonGroup = new javax.swing.ButtonGroup();
        toButtonGroup = new javax.swing.ButtonGroup();
        decimalRadio = new javax.swing.JRadioButton();
        binaryRadio = new javax.swing.JRadioButton();
        octalRadio = new javax.swing.JRadioButton();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        decimalRadio2 = new javax.swing.JRadioButton();
        binaryRadio2 = new javax.swing.JRadioButton();
        octalRadio2 = new javax.swing.JRadioButton();
        numberTextField = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Numeration Calculator");
        setBackground(new java.awt.Color(153, 153, 153));

        fromButtonGroup.add(decimalRadio);
        decimalRadio.setText("Decimal");
        decimalRadio.setName("decimalRadio"); // NOI18N
        decimalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalRadioActionPerformed(evt);
            }
        });

        fromButtonGroup.add(binaryRadio);
        binaryRadio.setText("Binary");
        binaryRadio.setName("binaryRadio"); // NOI18N
        binaryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryRadioActionPerformed(evt);
            }
        });

        fromButtonGroup.add(octalRadio);
        octalRadio.setText("Octal");
        octalRadio.setName("octalRadio"); // NOI18N
        octalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalRadioActionPerformed(evt);
            }
        });

        fromLabel.setText("Convert From:");
        fromLabel.setName("fromLabel"); // NOI18N

        toLabel.setText("Convert To:");
        toLabel.setName("toLabel"); // NOI18N

        toButtonGroup.add(decimalRadio2);
        decimalRadio2.setText("Decimal");
        decimalRadio2.setName("decimalRadio2"); // NOI18N
        decimalRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalRadio2ActionPerformed(evt);
            }
        });

        toButtonGroup.add(binaryRadio2);
        binaryRadio2.setText("Binary");
        binaryRadio2.setName("binaryRadio2"); // NOI18N
        binaryRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryRadio2ActionPerformed(evt);
            }
        });

        toButtonGroup.add(octalRadio2);
        octalRadio2.setText("Octal");
        octalRadio2.setName("octalRadio2"); // NOI18N
        octalRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalRadio2ActionPerformed(evt);
            }
        });

        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        inputLabel.setText("Input:");

        outputLabel.setText("Output:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decimalRadio)
                    .addComponent(fromLabel)
                    .addComponent(octalRadio)
                    .addComponent(binaryRadio))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binaryRadio2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(decimalRadio2)
                        .addComponent(toLabel))
                    .addComponent(octalRadio2))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputLabel)
                    .addComponent(inputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(convertButton)
                        .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalRadio)
                    .addComponent(decimalRadio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binaryRadio)
                    .addComponent(binaryRadio2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(octalRadio)
                    .addComponent(octalRadio2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertButton)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel)
                    .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        String input = numberTextField.getText();
        int in = Integer.parseInt(input);
        if(decimalRadio.isSelected()){
            if(binaryRadio2.isSelected()){
                outLabel.setText(decimalToBinary.decimalToBinary(in));
            }
            else if(decimalRadio2.isSelected()){
                outLabel.setText(input);
            }
            else if(octalRadio2.isSelected()){
                outLabel.setText(decimalToOctal.decimalToOctal(in));
            }
            else
                outLabel.setText("Select Output");
        }
        else if(binaryRadio.isSelected()){
            if(decimalRadio2.isSelected()){
                outLabel.setText(binaryToDecimal.binaryToDecimal(in));
            }
            else if(binaryRadio2.isSelected()){
                outLabel.setText(input);
            }
            else if(octalRadio2.isSelected()){
                String out = binaryToDecimal.binaryToDecimal(in);
                int result = Integer.parseInt(out);
                outLabel.setText(decimalToOctal.decimalToOctal(result));
            }
            else
                outLabel.setText("Select Output");
        }
        else if(octalRadio.isSelected()){
            if(decimalRadio2.isSelected()){
                outLabel.setText(octalToDecimal.octalToDecimal(in));
            }
            else if(binaryRadio2.isSelected()){
                String out = octalToDecimal.octalToDecimal(in);
                int result = Integer.parseInt(out);
                outLabel.setText(decimalToBinary.decimalToBinary(result));
            }
            else if(octalRadio2.isSelected()){
                outLabel.setText(input);
            }
            else 
                outLabel.setText("Select Output");
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextFieldActionPerformed

    private void decimalRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalRadioActionPerformed
        // TODO add your handling code here:
        if(decimalRadio.isSelected()){
            inputLabel.setText("Decimal:");
        }
    }//GEN-LAST:event_decimalRadioActionPerformed

    private void binaryRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryRadio2ActionPerformed
        // TODO add your handling code here:
        if(binaryRadio2.isSelected()){
            outputLabel.setText("Binary:");
        }
    }//GEN-LAST:event_binaryRadio2ActionPerformed

    private void decimalRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalRadio2ActionPerformed
        // TODO add your handling code here:
        if(decimalRadio2.isSelected()){
            outputLabel.setText("Decimal:");
        }
    }//GEN-LAST:event_decimalRadio2ActionPerformed

    private void binaryRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryRadioActionPerformed
        // TODO add your handling code here:
        if(binaryRadio.isSelected()){
            inputLabel.setText("Binary:");
        }
    }//GEN-LAST:event_binaryRadioActionPerformed

    private void octalRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalRadioActionPerformed
        // TODO add your handling code here:
        if(octalRadio.isSelected()){
            inputLabel.setText("Octal:");
        }
    }//GEN-LAST:event_octalRadioActionPerformed

    private void octalRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalRadio2ActionPerformed
        // TODO add your handling code here:
        if(octalRadio2.isSelected()){
            outputLabel.setText("Octal:");
        }
    }//GEN-LAST:event_octalRadio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binaryRadio;
    private javax.swing.JRadioButton binaryRadio2;
    private javax.swing.JButton convertButton;
    private javax.swing.JRadioButton decimalRadio;
    private javax.swing.JRadioButton decimalRadio2;
    private javax.swing.ButtonGroup fromButtonGroup;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JRadioButton octalRadio;
    private javax.swing.JRadioButton octalRadio2;
    private javax.swing.JLabel outLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.ButtonGroup toButtonGroup;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
